In [13]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import string

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

def preprocess(text):
    
    text = text.lower()

    
    text = text.translate(str.maketrans('', '', string.punctuation))

   
    words = word_tokenize(text)

  
    stop_words = set(stopwords.words('russian'))
    words = [word for word in words if word not in stop_words]


    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in words]

    return words


[nltk_data] Downloading package punkt to C:\Users\Хороший
[nltk_data]     человек\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Хороший
[nltk_data]     человек\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Хороший
[nltk_data]     человек\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [12]:
#Использую метода preprocess
with open("Далёкая радуга.txt", "r", encoding="utf-8") as file:
    raduga = file.read()

preprocess_raduga = preprocess(raduga)
print(preprocess_raduga)

['аркадий', 'стругацкий', 'борис', 'стругацкий', 'далёкая', 'радуга', '1', 'танина', 'ладонь', 'тёплая', 'немного', 'шершавая', 'лежала', 'глазах', 'дела', 'чувствовал', 'горько–солёный', 'запах', 'пыли', 'скрипели', 'спросонок', 'степные', 'птицы', 'сухая', 'трава', 'колола', 'щекотала', 'затылок', 'лежать', 'жёстко', 'неудобно', 'шея', 'чесалась', 'нестерпимо', 'двигался', 'слушая', 'тихое', 'ровное', 'дыхание', 'тани', 'улыбался', 'радовался', 'темноте', 'улыбка', 'наверное', 'неприличия', 'глупой', 'довольной', 'месту', 'ко', 'времени', 'лаборатории', 'вышке', 'заверещал', 'сигнал', 'вызова', 'пусть', 'первый', 'вечер', 'вызовы', 'месту', 'ко', 'времени', '–', 'робик', '–', 'шёпотом', 'сказала', 'таня', '–', 'слышишь', '–', 'совершенно', 'слышу', '–', 'пробормотал', 'роберт', 'помигал', 'пощекотать', 'танину', 'ладонь', 'ресницами', 'всё', 'далеко–далеко', 'совершенно', 'нужно', 'патрик', 'вечно', 'обалделый', 'недосыпания', 'далеко', 'маляев', 'своими', 'манерами', 'ледяного', 'сф

In [14]:
with open("Обитаемый остров.txt", "r", encoding="utf-8") as file:
    ostrov = file.read()

preprocess_ostrov = preprocess(ostrov)
print(preprocess_ostrov)

['глава', 'первая', 'максим', 'приоткрыл', 'люк', 'высунулся', 'опасливо', 'поглядел', 'небо', 'небо', 'низкое', 'какоето', 'твердое', 'легкомысленной', 'прозрачности', 'намекающей', 'бездонность', 'космоса', 'множественность', 'обитаемых', 'миров', '—', 'настоящая', 'библейская', 'твердь', 'гладкая', 'непроницаемая', 'твердь', 'эта', 'несомненно', 'опиралась', 'могучие', 'плечи', 'местного', 'атланта', 'равномерно', 'фосфоресцировала', 'максим', 'поискал', 'зените', 'дыру', 'пробитую', 'кораблем', 'дыры', '—', 'расплывались', 'две', 'большие', 'черные', 'кляксы', 'словно', 'капли', 'туши', 'воде', 'максим', 'распахнул', 'люк', 'настежь', 'соскочил', 'высокую', 'сухую', 'траву', 'воздух', 'горячий', 'густой', 'пахло', 'пылью', 'старым', 'железом', 'раздавленной', 'зеленью', 'жизнью', 'смертью', 'пахло', 'давней', 'непонятной', 'трава', 'пояс', 'неподалеку', 'темнели', 'заросли', 'кустарника', 'торчали', 'коекак', 'унылые', 'кривоватые', 'деревья', 'светло', 'яркую', 'лунную', 'ночь', '

In [15]:
with open("Пикник-на-обочине.txt", "r", encoding="utf-8") as file:
    picnik = file.read()

preprocess_picnik = preprocess(picnik)
print(preprocess_picnik)

['интервью', 'которое', 'специальный', 'корреспондент', 'хармонтского', 'радио', 'взял', 'доктора', 'ва', 'лентина', 'пильмана', 'случаю', 'присуждения', 'последнему', 'нобелевской', 'премии', 'физике', '19…', 'год', '–…вероятно', 'вашим', 'первым', 'серьѐзным', 'открытием', 'доктор', 'пильман', 'следует', 'считать', 'называемый', 'радиант', 'пильмана', '–', 'полагаю', 'радиант', 'пильмана', '–', 'это', 'первое', 'серьѐзное', 'собственно', 'крытие', 'моѐ', '–', 'вероятно', 'шутите', 'доктор', 'радиант', 'пильмана', '–', 'понятие', 'известное', 'всякому', 'школьни', 'ку', '–', 'это', 'удивляет', 'радиант', 'пильмана', 'открыт', 'впервые', 'именно', 'школьником', 'сожалению', 'помню', 'звали', 'посмотрите', 'стетсона', '«', 'истории', 'посещения', '»', '–', 'всѐ', 'это', 'подробно', 'рассказано', 'открыл', 'радиант', 'впервые', 'школьник', 'опубликовал', 'координаты', 'впер', 'вые', 'студент', 'назвали', 'радиант', 'почемуто', 'моим', 'именем', '–', 'открытиями', 'происходят', 'удивитель

In [16]:
with open("Понедельник начинается в субботу.txt", "r", encoding="utf-8") as file:
    ponedelnik = file.read()

preprocess_ponedelnik = preprocess(ponedelnik)
print(preprocess_ponedelnik)

['история', 'первая', 'суета', 'вокруг', 'дивана', 'учитель', 'дети', 'запишите', 'предложение', '«', 'рыба', 'сидела', 'дереве', '»', 'ученик', 'рыбы', 'сидят', 'деревьях', 'учитель', 'ну…', 'это', 'сумасшедшая', 'рыба', 'школьный', 'анекдот', 'приближался', 'месту', 'моего', 'назначения', 'вокруг', 'прижимаясь', 'самой', 'дороге', 'зеленел', 'лес', 'изредка', 'уступая', 'место', 'полянам', 'поросшим', 'желтой', 'осокой', 'солнце', 'садилось', 'который', 'час', 'никак', 'могло', 'сесть', 'висело', 'низко', 'горизонтом', 'машина', 'катилась', 'узкой', 'дороге', 'засыпанной', 'хрустящим', 'гравием', 'крупные', 'камни', 'пускал', 'колесо', 'каждый', 'багажнике', 'лязгали', 'громыхали', 'пустые', 'канистры', 'справа', 'леса', 'вышли', 'двое', 'ступили', 'обочину', 'остановились', 'глядя', 'мою', 'сторону', 'поднял', 'руку', 'сбросил', 'газ', 'рассматривая', 'это', 'показалось', 'охотники', 'молодые', 'люди', 'немного', 'старше', 'лица', 'понравились', 'остановился', 'поднимал', 'руку', 'п

In [17]:
with open("Стажеры.txt", "r", encoding="utf-8") as file:
    stageri = file.read()

preprocess_stageri = preprocess(stageri)
print(preprocess_stageri)

['подкатил', 'громадный', 'краснобелый', 'автобус', 'отлетающих', 'пригласили', 'садиться', 'ступайте', 'сказал', 'дауге', 'быков', 'проворчал', 'успеем', 'пока', 'усядутся', 'исподлобья', 'смотрел', 'пассажиры', 'другим', 'неторопливо', 'поднимаются', 'автобус', 'пассажиров', 'человек', 'сто', 'это', 'минут', 'пятнадцать', 'меньше', 'солидно', 'заметил', 'гриша', 'быков', 'строго', 'посмотрел', 'застегни', 'рубашку', 'сказал', 'пап', 'жарко', 'сказал', 'гриша', 'застегни', 'рубашку', 'повторил', 'быков', 'ходи', 'расхлюстанный', 'бери', 'пример', 'сказал', 'юрковский', 'тебе', 'дауге', 'взглянул', 'отвел', 'глаза', 'хотелось', 'смотреть', 'юрковского', 'уверенное', 'рыхловатое', 'лицо', 'брюзгливо', 'отвисшей', 'нижней', 'губой', 'тяжелый', 'портфель', 'монограммой', 'роскошный', 'костюм', 'редкостного', 'стереосинтетика', 'глядеть', 'высокое', 'прозрачное', 'небо', 'чистое', 'синее', 'единого', 'облачка', 'птиц', 'аэродромом', 'разгоняли', 'ультразвуковыми', 'сиренами', 'быковмладший

In [18]:
with open("Трудно быть богом.txt", "r", encoding="utf-8") as file:
    bog = file.read()

preprocess_bog = preprocess(bog)
print(preprocess_bog)

['ложа', 'анкиного', 'арбалета', 'выточена', 'черной', 'пластмассы', 'тетива', 'хромистой', 'стали', 'натягивалась', 'одним', 'движением', 'бесшумно', 'скользящего', 'рычага', 'антон', 'новшеств', 'признавал', 'доброе', 'боевое', 'устройство', 'стиле', 'маршала', 'тоца', 'короля', 'пица', 'первого', 'окованное', 'черной', 'медью', 'колесиком', 'которое', 'наматывался', 'шнур', 'воловьих', 'жил', 'касается', 'пашки', 'взял', 'пневматический', 'карабин', 'арбалеты', 'считал', 'детством', 'человечества', 'ленив', 'неспособен', 'столярному', 'ремеслу', 'причалили', 'северному', 'берегу', 'желтого', 'песчаного', 'обрыва', 'торчали', 'корявые', 'корни', 'мачтовых', 'сосен', 'анка', 'бросила', 'рулевое', 'весло', 'оглянулась', 'солнце', 'поднялось', 'лесом', 'голубое', 'зеленое', 'желтое', '—', 'голубой', 'туман', 'озером', 'темнозеленые', 'сосны', 'желтый', 'берег', 'той', 'стороне', 'небо', 'всем', 'этим', 'ясное', 'белесоватосинее', '—', '—', 'сказал', 'пашка', 'ребята', 'сидели', 'перегну

2. Косинусное сходство


In [22]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

path1 = r'C:\Users\Хороший человек\Desktop\DeepAutomation\dz.predobrabotka\Далёкая радуга.txt'
with open(path1, 'r', encoding='utf-8') as f:
    text1 = f.read()

path1 = r'C:\Users\Хороший человек\Desktop\DeepAutomation\dz.predobrabotka\Обитаемый остров.txt'
with open(path1, 'r', encoding='utf-8') as f:
    text2 = f.read()

path1 = r'C:\Users\Хороший человек\Desktop\DeepAutomation\dz.predobrabotka\Пикник-на-обочине.txt'
with open(path1, 'r', encoding='utf-8') as f:
    text3 = f.read()

path1 = r'C:\Users\Хороший человек\Desktop\DeepAutomation\dz.predobrabotka\Понедельник начинается в субботу.txt'
with open(path1, 'r', encoding='utf-8') as f:
    text4 = f.read()

path1 = r'C:\Users\Хороший человек\Desktop\DeepAutomation\dz.predobrabotka\Стажеры.txt'
with open(path1, 'r', encoding='utf-8') as f:
    text5 = f.read()

path1 = r'C:\Users\Хороший человек\Desktop\DeepAutomation\dz.predobrabotka\Трудно быть богом.txt'
with open(path1, 'r', encoding='utf-8') as f:
    text6 = f.read()


# Конвертирую текста в векторы
vectorizer = CountVectorizer().fit_transform([text1, text2, text3, text4, text5, text6])
vectors = vectorizer.toarray()

# Вычисляю косинусное сходства
cosine_sim = cosine_similarity(vectors)

# Вывожу косинусную матрицу
print(cosine_sim)


[[1.         0.76909216 0.8368898  0.63281379 0.70458795 0.64327212]
 [0.76909216 1.         0.8362717  0.61517187 0.64989748 0.6536743 ]
 [0.8368898  0.8362717  1.         0.70487155 0.71753116 0.69545693]
 [0.63281379 0.61517187 0.70487155 1.         0.61480519 0.58445073]
 [0.70458795 0.64989748 0.71753116 0.61480519 1.         0.61133264]
 [0.64327212 0.6536743  0.69545693 0.58445073 0.61133264 1.        ]]
